Azure/terraform-azurerm-aks

main.tf
Update the azurerm provider to 1.23.0 to make way for integrating the aad rbac feature.
=> Bump azurerm provider to 1.23.0

main.tf
This is required for several compliance checks.
=> Added tags to azurerm_log_analytics_solution

README.md, main.tf, test/fixture/main.tf, variables.tf
```
Using bundler 2.1.4
Using colorize 0.8.1
Using terramodtest 0.7.0 from https://github.com/Azure/terramodtest.git (at master@b1f51e0)
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Using dep ensure to install required go packages.
[0;33;49mINFO: Styling Terraform configurations...
[0m[0;32;49mINFO: Done!
[0m[0m[1mInitializing modules...[0m
- ssh-key in modules/ssh-key
[0m[1mInitializing the backend...[0m
[0m[1mInitializing provider plugins...[0m
- Finding latest version of hashicorp/azurerm...
- Finding latest version of hashicorp/tls...
- Finding latest version of hashicorp/local...
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)
- Installing …
```
=> Allow to enable Kubernetes Dashboard

README.md, main.tf, test/fixture/main.tf, test/fixture/outputs.tf, variables.tf
Allow users to set the Kubernetes cluster version they want to use, otherwise default to the latest non-preview release available.
=> Allow the ability to specify a Kubernetes release version

README.md, main.tf, test/fixture/main.tf, variables.tf
=> Edit the 'default_node_pool' and 'network_profile' config blocks

README.md, main.tf, test/fixture/main.tf, variables.tf
Enhancement for `ingress_application_gateway` support based on @generalconsensus pr #99 , solving issue #115 .
=> Enhancement for `ingress_application_gateway` support

main.tf, variables.tf
This patch added `nullable` argument to some bool type variables to make them real "Bool", avoid ambiguous `null` value.
Related to #186
=> Add `nullable` argument to some bool type variables.

main.tf
Add index to `to` address to fix #225
=> Add index to `to` address to fix #225

README.md, versions.tf
This pr should fix #228 issue.
=> Loose the restriction on tls provider's version to include major version greater than 3.0

.github/workflows/pr-check.yaml
Add a CI step to detect potential breaking changes.
=> Add breaking change detect CI step.

main.tf, variables.tf
=> Support for Proximity placement group for default node pool

NoticeOnUpgradeTov7.0.md
Improve information to upgrade to 7.0
#418
=> Improve information to upgrade to 7.0

examples/application_gateway_ingress/main.tf, examples/startup/main.tf, examples/with_acr/main.tf
=> bump k8s version for example since 1.26 has been deprecated

.github/workflows/weekly-codeql.yaml
=> Add weekly-codeql action

.devcontainer/devcontainer.json
Restore the `.devcontainer` folder that was removed by a glitch in the automation.
@lonegunmanb please review. thanks
=> Restore devcontainer

README.md
Fix README.md format issues on Github rendering
=> fix README.md format

examples/application_gateway_ingress/main.tf, examples/startup/main.tf, examples/with_acr/main.tf
=> Bump examples to AKS 1.30

test/go.mod
Dependabot changes from PR 609 619 620
=> Dependabot changes from PR 609 619 620

test/go.mod
PR with summary of dependabot proposed changes
=> Dependabot 624 626

examples/multiple_node_pools/README.md, examples/multiple_node_pools/main.tf, examples/multiple_node_pools/variables.tf
Release pr for #501 
Write scenario to test AKS Kubernetes upgrades where Kubernetes control plane is upgraded first, and the node pools are upgraded in a second step.
#465
=> Extend multiple_node_pools example to test AKS upgrades

main.tf, variables.tf
Release pr for #659
But I'd like to preserve the validation, as `precondition`
=> Refactor variable validation that only works in terraform 1.9 and newer

locals.tf
=> Fix incorrect private dns zone regex

v4/extra_node_pool_override.tf
=> Add missing temporary_name_for_rotation to v4 nodepool create_after_destroy override

README.md, examples/application_gateway_ingress/main.tf, examples/multiple_node_pools/main.tf, extra_node_pool.tf, main.tf, outputs.tf
=> output aks `node_resource_group_id`

README.md
=> update readme to add upgrade notice
