Azure/terraform-azurerm-aks

README.md, main.tf, modules/kubernetes-cluster/main.tf, modules/kubernetes-cluster/variables.tf, variables.tf
Makes the hardcoded Kubernetes version in the kubernetes-cluster submodule configurable.
https://github.com/Azure/terraform-azurerm-aks/blob/7e38320cbec6d4e10b57780d65406c521b8e906d/modules/kubernetes-cluster/main.tf#L6
Fixes #6
=> Configurable Kubernetes version in module

README.md, modules/kubernetes-cluster/outputs.tf, outputs.tf
Exposes the cluster info outside of this terraform module so they may be used to set up the terraform azurerm provider. See the README for an example of how to provide the outputs to the kubernetes provider.
=> Expose cluster connection info

modules/log-analytics-solution/main.tf
The variable `workspace_name` was defined twice causing an error on `terraform init`. This value should correspond to the name of the Azure Log Analytics workspace which it'll be working with.
See https://www.terraform.io/docs/providers/azurerm/r/log_analytics_solution.html#workspace_name
=> fix #21 delete duplicate workspace_name

main.tf, modules/kubernetes-cluster/main.tf, modules/kubernetes-cluster/outputs.tf, modules/kubernetes-cluster/variables.tf, modules/log-analytics-solution/main.tf, modules/log-analytics-solution/outputs.tf, modules/log-analytics-solution/variables.tf, modules/log-analytics-workspace/main.tf, modules/log-analytics-workspace/outputs.tf, modules/log-analytics-workspace/variables.tf, modules/ssh-key/main.tf, outputs.tf, test/fixture/main.tf, variables.tf, versions.tf
Upgraded to terraform version 0.12. This PR is on top of a previous bugfix (#21) and the only major change is the `azurerm` version in the fixture has changed from `=1.16.0` to `~> 1.27`, which is the lowest version the azure provider supports terraform 0.12.
=> fix #20, Upgrade to v12

README.md, main.tf, outputs.tf, test/fixture/main.tf, test/fixture/outputs.tf, variables.tf
Fix https://github.com/Azure/terraform-azurerm-aks/issues/50
Sorry for the previous not merged `http_application_routing_zone_name` has to be added again here.
=> Make `client_id` `client_secret` Optional, add `SystemAssigned` identity if service principal is not set

.github/pull_request_template.md, Dockerfile, Gemfile, Rakefile
Fixes #000 
Integration of Terramodtest 0.8.0
=> Integration of Terramodtest 0.8.0

versions.tf
Support for `tags` in `azurerm_log_analytics_solution` has been added in v2.34.0
=> Set minimal provider required version

README.md, main.tf, test/fixture/main.tf, variables.tf
I tried to run the tests, but I can't build the azure-aks image anymore:
```shell
docker build --no-cache --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t azure-aks .
Sending build context to Docker daemon  719.4kB
Step 1/28 : ARG BUILD_TERRAFORM_VERSION="0.13.5"
Step 2/28 : FROM mcr.microsoft.com/terraform-test:${BUILD_TERRAFORM_VERSION}
---> 66859ff1c069
Step 3/28 : ARG MODULE_NAME="terraform-azurerm-aks"
---> Running in de6cb6b5b931
Removing intermediate container de6cb6b5b931
---> 4717706e9412
Step 4/28 : ARG BUILD_ARM_SUBSCRIPTION_ID=""
---> Running in 74e8b7de6720
Removing intermediate container 74e8b7de6720
---> …
```
=> Support setting network_plugin

README.md, main.tf, test/fixture/main.tf, variables.tf
Hello, this is my first PR for this project. I've started using this module recently to manage my AKS cluster in my infrastructure.
I've added new variable because I'd like to restrict cluster access from internet in my infrastructure.
This change doesn't broke module behaviour because default is `false`. Default AKS cluster installation exposes API over internet as before.
Please let me know how do you think about this change.
=> Add support for private cluster API access.

README.md, main.tf, test/fixture/main.tf, variables.tf
Add support for nodepool autoscaling with the following configuration to the module:
```hcl
enable_auto_scaling  = true
agents_min_count     = 1
agents_max_count     = 2
```
Note: To build the custom image to run the tests I needed to comment the following lines on the Dockerfile:
```dockerfile
```
Otherwise, the following error would happen:
```
---> Using cache
---> 46c203d86fc0
Step 18/28 : RUN mkdir /go
---> Running in e91071d40948
mkdir: cannot create directory ‘/go’: File exists
The command '/bin/sh -c mkdir /go' returned a non-zero code: 1
```
The base image already has the `go` folders in it.
=> Add support for nodepool autoscaling

versions.tf
Fixes #81 
Removes patch version constraint so that minor versions of new azurerm providers are allowed.
=> Change Version Constraint to allow for minor Azurerm Provider releases

main.tf, test/fixture/main.tf, variables.tf
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>
If you try to disable log-analytics in existing cluster with enabled oms plugin you will get such error:
```
Error: waiting for update of Managed Kubernetes Cluster "<cluster_name>" (Resource Group "<rg_name>"): Code="GetLogAnalyticsWorkspaceError" Message="Unable to get log analytics workspace info. Resource ID: /subscriptions/<subscription_id>/resourcegroups/<rg_name>/providers/microsoft.operationalinsights/workspaces/<log_analytics_workspace_id>. Details: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.OperationalInsights/workspaces/<log_analytics_workspace_id>' under resource group '<rg_name>' was not found. For more details please go to …
```
=> Fixed disabling oms-plugin

main.tf
**Changes proposed in the pull request**
To make the `default_node_pool` nested block `dynamic`, with content based on value of `enable_auto_scaling` input variable. In example, the `node_count` parameter of `default_node_pool` should be set only when autoscaling is disabled.
Tests pass.
Fixes #91
=> Do not set default node pool node_count when auto scaling is enabled

outputs.tf
Fixes #94 
Mark kube_config_raw output as non-sensitive.
`kube_config_raw` needs to be marked as nonsensitive to work with terraform v0.15
=> Mark kube_config_raw output as non-sensitive.

README.md, main.tf, test/fixture/main.tf, variables.tf
Fixes #000 
This PR adds the cluster_name variable.
=> Add cluster_name variable

README.md, main.tf, test/fixture/main.tf, variables.tf, versions.tf
This PR adds support for default pool [host-based encryption](https://docs.microsoft.com/en-us/azure/aks/enable-host-encryption).
* there is a new `enable_host_encryption` variable, that default to `false` and can be turned to `true` to enable host-based encryption
* the documentation has been updated with this new flag
* the tests have been updated with this new flag
* the minimum AzureRM provider version has been moved to `2.46` which corresponds to the release of this property in the provider
=> Add support for default pool host-based encryption

outputs.tf
Added output for ```kube_admin_config_raw``` so this can be used to automate day 2 operations after the deployment has been done.
=> Added output for kube_admin_config_raw

main.tf, variables.tf
This PR close https://github.com/Azure/terraform-azurerm-aks/issues/135
=> Include node_resource_group as variable

README.md
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group
`display_name` is a valid argument. `name` as in the Readme is invalid.
Fixes #150 and #159
=> Trivial fix to the example in the README

outputs.tf
Export the addon_profile attributes in order to make these consumable by other resources.
=> export addon_profile attributes

main.tf, variables.tf
Fixes #114 
Changes proposed in the pull request: Finally add `os_disk_type`
=> Add `os_disk_type` for node pools

main.tf, test/fixture/main.tf, variables.tf
This allows to define `location` for the resources explicitly. Because if you have slight diffs on the resource group (like for instance a label being propagated by a mitigating policy), then terraform will say that the `location` is only known after apply, and this will again trigger a recreate on the cluster - blowing the whole cluster away.
The change is backwards-compatible, as the new parameter is opt-in, and old behaviour of reading location from resource-group is preserved.
=> workaround for recreate bug

test/fixture/main.tf, test/terraform_aks_test.go
Trivial, running `terraform fmt -recursive` against the repo. I spotted this while testing the CI branch
=> Fixing 'terraform fmt' linting

variables.tf
`tags` variable is not related to Virtual Network resources, it is related to AKS cluster resources instead. Therefore, this PR improves the description for this variable.
=> Improve "tags" variable description

README.md, main.tf, outputs.tf, test/fixture/main.tf, test/fixture/outputs.tf, variables.tf, versions.tf
Fixes #145
Fixes #156
Upgrade azurerm to 3.3.0 following the upgrade guide https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_kubernetes_cluster
Tests succesful:
```
TestTerraformBasicExample 2022-04-22T11:25:27Z command.go:96: Destroy complete! Resources: 18 destroyed.
--- PASS: TestTerraformBasicExample (1473.05s)
PASS
ok      terraform-azurerm-aks/test      1473.061s
```
---
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
=> chore(azurerm): upgrade to 3.3.0

outputs.tf
This patch will fix both #180 and #182.
As `addon_profile` was added by @davidkarlsen, would you please give this pr a review to see whether the new output object can work with your code? Thanks!
=> Refactor output for removed `addon_profile` block. Deprecate legacy dot index syntax in outputs.

main.tf, variables.tf, versions.tf
Fixes #204
The flag oidc_issuer_enabled is now a required parameter on the `azurerm_kubernetes_cluster` resource. Adding support for it.
=> feat: add support for OIDC issuer

outputs.tf
Pull request https://github.com/Azure/terraform-azurerm-aks/pull/205 has added support for enabling the OIDC issuer to be created with the AKS cluster.
This small PR adds support for also exposing the created issuer URL from the module to the caller. 
Note: Should have probably been part of the original PR, sorry for the noise.
=> chore: output oidc_issuer_url from module

README.md, versions.tf
Fixes #000 
Changes proposed in the pull request: The `variables.tf` is using a feature introduced with Terraform version `v1.1.0` which is called [Disallowing Null Input Values](https://www.terraform.io/language/values/variables#disallowing-null-input-values). To prevent Errors during a Terraform run, I added this version constraint and run fmt/terraform-docs.
Tried to run the tests and they fail with Terraform version `0.14.4` obviously. But seems like there is no Image with tag `1.1.0`. If using the latest version of the image, Terraform version `0.12.10` is installed...
=> feat(versions.tf): TF version must be >= 1.1.0

main.tf, test/fixture/main.tf, test/fixture/outputs.tf, variables.tf
Add arguments to `azure_active_directory_role_based_access_control` block, turn rbac in test code. 
Related to #198 and #183
=> Add arguments to `azure_active_directory_role_based_access_control` block, turn rbac in test code on.

main.tf, test/fixture/main.tf, variables.tf
Rename `var.enable_azure_policy` to `var.azure_policy_enabled` to meet the naming convention.
Set `azure_policy_enabled` to true in test fixture code.
Related to #202 and #183
=> Uses Azure policies add-on in the test fixture code

main.tf, variables.tf
Allows for `only_critical_addons_enabled` to be enabled for the aks clusters default node pool.
=> add support for setting `only_critical_addons_enabled`

main.tf, variables.tf
Add support for the argument `key_vault_secrets_provider`:
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_vault_secrets_provider
* https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
Note that the output for this feature was already implemented in the `output.tf` file.
Fixes #210
=> Add key_vault_secrets_provider

README.md, main.tf, variables.tf
Fixes https://github.com/Azure/terraform-azurerm-aks/issues/120
Added an optional input variable to accept private_dns_zone_id
First time contributing to this repo. Hopefully, this helps. The tests passed and ran terrafmt.
BTW: Sorry about the closed, duplicate, unmerged pull requests. Third time is the charm! 😄
=> Adding the private_dns_zone_id input variable

test/fixture/main.tf
According to [BridgeCrew Checkov's policy](https://docs.bridgecrew.io/docs/ensure-that-aks-enables-private-clusters), we should ensure AKS enables private clusters. 
Related to #183 and fix #217.
=> Enable private cluster for the test code.

main.tf, test/fixture/main.tf, variables.tf
Make `local_account_disabled` configurable to fix #216.
=> Make `local_account_disabled` configurable to fix #216.

main.tf, outputs.tf
Create the tls-private-key only if needed to avoid confusion with users not knowing the codebase.
The users might expect to use the private key when it is created, so it should not be created at all if there is no use for it.
=> Create tls-private-key only if needed

main.tf, test/fixture/disk_encryption_set.tf, test/fixture/main.tf, test/fixture/providers.tf, test/fixture/variables.tf, variables.tf
This patch add support for `disk_encryption_set_id` to harden the cluster's security and solve #194 . We've used Checkov and Tflint to scan the test code and ignore one issue by comment. This patch should partially solve #183.
=> Add support for `disk_encryption_set_id`

main.tf, variables.tf
Make `api_server_authorized_ip_ranges` configurable.
Fix #208 and #108
=> Make `api_server_authorized_ip_ranges` configurable.

main.tf, outputs.tf, test/fixture/outputs.tf, variables.tf, versions.tf
Rename `var.system_assigned_identity` to `cluster_identity`, add validation and precondition for identity-related variables. Bump Terraform required version to 1.2.0 since we've used precondition. #196 related.
=> Improve identity related variables and output.

variables.tf
This is a regression introduced when merging PR #149 
There is a duplicated variable:
```
│ Error: Duplicate variable declaration
│ 
│   on .terraform/modules/aks/variables.tf line 409:
│  409: variable "private_dns_zone_id" {
│ 
│ A variable named "private_dns_zone_id" was already declared at .terraform/modules/aks/variables.tf:391,1-31. Variable names must be unique within a
│ module.
```
=> Delete duplicated variable private_dns_zone_id

outputs.tf
Using the latest 5.0.0 + terragrunt, I have run into the following errors:
```bash
### shortened for clarity 
azurerm_kubernetes_cluster.main: Creation complete after 11m7s [id=/subscriptions/xxxx/resourceGroups/resource-group/providers/Microsoft.ContainerService/managedClusters/yyyy]
│ Error: Output refers to sensitive values
│   on outputs.tf line 11:
│   11: output "admin_client_certificate" {
│   16: output "admin_client_key" {
│   21: output "admin_cluster_ca_certificate" {
│   26: output "admin_host" {
│   31: output "admin_password" {
│   36: output "admin_username" {
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ …
```
=> fix: mark outputs as sensitive

main.tf, variables.tf
Adds support for a `microsoft_defender` block introduced with https://github.com/hashicorp/terraform-provider-azurerm/pull/16218/
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
=> feat(aks): add microsoft defender support

CHANGLOG.md, README.md, versions.tf
When using AKS 1.24 the `hashicorp/terraform-provider-azurerm` provider has some bugs that result in a empty `kube_config` in the terraform state:
* https://github.com/hashicorp/terraform-provider-azurerm/issues/17182
* https://github.com/hashicorp/terraform-provider-azurerm/issues/18139
The version 3.21.0 is the minimum version that contains those fixes.
Fixes #236
(waiting for version 3.21.0 to be actually released https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md)
=> Update hashicorp/terraform-provider-azurerm to version 3.21.0 (fixes for AKS 1.24)

README.md
The example path in the readme file is incorrect now.
=> Fix example path in readme file.

.github/workflows/pr-check.yaml
=> align pr-check with local machine by using docker command instead

.github/ISSUE_TEMPLATE/Bug_Report.yml
I was opening a bug and the green "Submit new issue" button was disabled because of a missing required value. I spent a lot of time understanding what the problem was because I could not distinguish the placeholder from the actual value:
This patch improves the placeholders so that it is more visibile if the user forgot to enter actual data.
=> Improve placeholders for visibility in the UX

examples/named_cluster/main.tf, locals.tf, main.tf, test/unit/unit_test.go, unit-test-fixture/alt_locals.tf, unit-test-fixture/locals.tf, unit-test-fixture/outputs.tf, unit-test-fixture/variables.tf
This pr introduce unit test for complex logic inside `locals` block.
=> Add unit test for complex local logic

.gitignore
This pr add `scritps` soft link generated by tfmod-scaffold to `.gitignore` file.
=> Ignore `scripts` soft link

locals.tf, main.tf, test/unit/unit_test.go
This is an addition to PR #281
In AKS is possible to upgrade the control plane and the kubernetes nodes independently. The Terraform resource `azurerm_kubernetes_cluster` exposes this with 2 variables `kubernetes_version` and  `orchestrator_version`.
In PR #281 the lifecycle validation check takes into account only `kubernetes_version`.
Related to  #280
=> auto-upgrade: variable orchestrator_version to null

examples/named_cluster/key_vault.tf, examples/startup/disk_encryption_set.tf, examples/without_monitor/disk_encryption_set.tf
This pull request amended the missing Key Vault keys permissions that examples require now.
#316
=> Fix #316 `current client lacks permissions to read Key Rotation Policy` issue

examples/multiple_node_pools/main.tf
The `multiple_node_pools` example failed the test because we didn't set `vnet_subnet_id`. This pr fixed this issue.
#000
=> Fix example multiple_node_pools

main.tf
=> [Breaking] - Fix #315 by amending missing `linux_os_config` block

examples/multiple_node_pools/main.tf, examples/named_cluster/main.tf, examples/startup/main.tf, examples/with_acr/main.tf, examples/without_monitor/main.tf, main.tf
=> Check `api_server_authorized_ip_ranges` when `public_network_access_enabled` is `true`

NoticeOnUpgradeTov7.0.md
=> Upgrade notice for v7.0

main.tf
Assign network contributor role to control plane identity.
Now it is currently using the kubelet identity which is wrong.
Relevant docs:
https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities
Fixes #368
=> assign network contributor role to control plane identity

locals.tf
As #364 described, sometimes `local.subnet_ids` would contain `null` value, and that could cause error as the set is used as `for_each` iterator. This pr filtered `null` value out of the set to solve the issue.
#364 
=> Filter null value out from `local.subnet_ids`

README.md, examples/named_cluster/main.tf, examples/named_cluster/variables.tf, main.tf, test/e2e/terraform_aks_test.go
As #344 described, this module would cause an error once we'd like to deploy an aks cluster with a log analytics workspace that is located in another region.
This pr added a data source to read the workspace's location to avoid this issue. It also added a new e2e test `TestExamples_differentLocationForLogAnalyticsSolution` to verify it.
#344 
=> User `location` returned from data source for log analytics solution.

test/e2e/terraform_aks_test.go
The e2e test `TestExamples_differentLocationForLogAnalyticsSolution` would failed when we run e2e test on our local machine because of the incorrect initialization. This pr fixed this incorrect e2e test.
#000
=> Fix incorrect e2e test code so it could pass on our local machine

examples/named_cluster/key_vault.tf, examples/startup/disk_encryption_set.tf, examples/without_monitor/disk_encryption_set.tf
We used to call `https://api.ipify.org?format=json` to retrieve our current public ip, but sometimes the API is unstable, and the returned temporary errors might break our e2e tests and cause the waste of time.
This pr improves that by calling [public-ip module](https://registry.terraform.io/modules/lonegunmanb/public-ip/lonegunmanb/latest), the module would fetch the public IP address from three different public APIs to ensure reliability and fallback support.
#000
=> Use `lonegunmanb/public-ip/lonegunmanb` module to retrieve public ip

examples/startup/main.tf, main.tf, variables.tf
=> Add support for `maintenance_window_node_os` block

main.tf
Using `Overlay` instead of `overlay` triggers unnecessary cluster updates.
Fixing to user lowercase only everywhere.
https://github.com/Azure/terraform-azurerm-aks/issues/429 
https://github.com/hashicorp/terraform-provider-azurerm/issues/22621
=> use lowercase everywhere for network plugin mode overlay

README.md, outputs.tf
This add `web_app_routing_identity` to outputs, which is needed for role assignments when DNS zone and AKS Cluster are in different resource groups.
=> Add web_app_routing_identity block to outputs

test/e2e/terraform_aks_test.go, test/upgrade/upgrade_test.go
This module might tried to create azure application gateway as cluster's ingress,  sometimes when the e2e test tried to read ingress's url, the agw was not ready yet. This pr added a retry in the test code. 
=> Add retry when the ingress is not ready

extra_node_pool.tf
Remove precondition on extra node pool which prevent using windows pool with overlay since the feature is now GA
#511 
=> Remove precondition on extra node pool which prevent using windows pool with overlay

NoticeOnUpgradeTov8.0.md, README.md
=> Add upgrade notice document

examples/application_gateway_ingress/outputs.tf, test/e2e/terraform_aks_test.go
We need to compromise on e2e tests involving application gateway ingress, since the creation of ingress is not stable, and broke e2e tests from time to time. To improve the stability of tests, I'd like to make a compromise, for now, until I figure out the root cause.
#000
=> Compromise on e2e tests involving ingress, since it's not stable

README.md, outputs.tf
=> fix(typo): typo in output variable

examples/named_cluster/key_vault.tf, examples/named_cluster/main.tf, test/go.mod
Running Microsoft Terraform module AKS end to end tests I get this new error message I have never seen before from the ARM API:
https://github.com/Azure/terraform-azurerm-aks/actions/runs/11665268834/job/32477571013?pr=598#step:3:6605
HTTP 400 "Vnet integration should be enabled when KeyVault network access is Private."
I believe this is the root cause:
https://learn.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption#prerequisites ( See yellow warning box)
However Vnet Integration is still preview as far as I know. Terraform provider azurerm V4 will not support preview features. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api
This is a workaround to get the CI running again.
This PR needs to be reverted once AKS …
=> Make the Azure Key Vault public because private Key Vault requires preview API

main.tf, variables.tf
Option to enable or disable OMS agent(Azure Monitor) add-on
#600
=> Support of oms_agent_enabled add-on

role_assignments.tf
Local branch for PR #629
( cannot run E2E tests on PRs from external forks )
=> Add nonsensitive around for_each argument

v4/main_override.tf, v4/variables_override.tf, variables.tf
Makes the `upgrade_override` block configurable on the kubernetes cluster.
This is important because if force upgrade is ever used via the cli the cluster cannot be modified via terraform unless that block is present.
Context:
I used the force-upgrade via the CLI to upgrade one of my clusters back in November. The `upgrade_override` block was detected and state updated. Now months later im starting the next upgrade cycle and this cluster cannot be updated as the `upgrade_override` block cannot be removed if present
```
│ Error: `upgrade_override` cannot be unset
│
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on ../azure-aks-azurerm/v4/main.tf line 13, in resource "azurerm_kubernetes_cluster" "main":
│   13: resource "azurerm_kubernetes_cluster" "main" {
│
╵
```
Thanks for your …
=> Add upgrade_override block to azurerm_kubernetes_cluster main

variables.tf
Module cannot be used with terraform older than `1.9` despite only requiring >= `1.3` because it is doing [variable cross validation](https://www.hashicorp.com/en/blog/terraform-1-9-enhances-input-variable-validations). 
Since `1.9` is after the license change in `1.6`, I removed the validation rather than bumping the required terraform version to `1.9`
Extra context: I tried using `10.0.0-beta` now that it supports the `upgrade_override` block and the module is throwing error on init for invalid variable validation
```
Downloading registry.terraform.io/Azure/aks/azurerm 10.0.0-beta for aks...
- aks in .terraform/modules/aks/v4
╷
│ Error: Invalid reference in variable validation
│
│   on .terraform/modules/aks/v4/variables.tf line 398, in variable "client_id":
│  398:     condition     = …
```
=> Remove variable validation that only works in terraform 1.9 and newer

NoticeOnUpgradeTov10.0.md, README.md
=> Add `v10` upgrade notice

v4/extra_node_pool_override.tf
The azurerm provider still expects temporary_name_for_rotation to be set when any of the notable properties change on the node pool whether created before or after destroy (https://registry.terraform.io/providers/hashicorp/azurerm/4.33.0/docs/resources/kubernetes_cluster_node_pool)
It gives an error:
` Error: `temporary_name_for_rotation` must be specified when updating any of the following properties ["fips_enabled" "host_encryption_enabled" "kubelet_config" "kubelet_disk_type" "linux_os_config" "max_pods" "node_public_ip_enabled" "os_disk_size_gb" "os_disk_type" "pod_subnet_id" "snapshot_id" "ultra_ssd_enabled" "vm_size" "vnet_subnet_id" "zones"]`
Just adding the missing property to the create_after_destroy node pool in the v4 overrides
Mentioned in …
=> Add missing temporary_name_for_rotation to v4 nodepool create_after_destroy override

NoticeOnUpgradeTov11.0.md, main.tf, outputs.tf
This PR fixes issue #683 where the `cluster_identity` output was incorrectly marked as sensitive, forcing users to mark their own outputs as sensitive unnecessarily.
- **main.tf**: Updated the `identity` dynamic block to use `nonsensitive(var.client_secret)` in the `for_each` expression to prevent sensitivity propagation
- **outputs.tf**: Removed `sensitive = true` flag from the `cluster_identity` output 
- **NoticeOnUpgradeTov11.0.md**: Added documentation for this breaking change
The issue occurred because the `identity` block's `for_each` expression referenced `var.client_secret`, which is marked as sensitive. This caused Terraform to treat the entire identity block as sensitive, even though the identity information (principal_id, tenant_id, type) is not actually sensitive data.
- …
=> 🤖 fix: remove incorrect sensitive flag from `cluster_identity` output
